// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

library AssetsArbitrum {
  // https://arbiscan.io/address/0x82aF49447D8a07e3bd95BD0d56f35241523fBab1
  address internal constant WETH = 0x82aF49447D8a07e3bd95BD0d56f35241523fBab1;

  // https://arbiscan.io/address/0x8c6Bd546fB8B53fE371654a0E54D7a5bD484b319
  address internal constant GOA = 0x8c6Bd546fB8B53fE371654a0E54D7a5bD484b319;

  // https://arbiscan.io/address/0x912CE59144191C1204E64559FE8253a0e49E6548
  address internal constant ARB = 0x912CE59144191C1204E64559FE8253a0e49E6548;

  // https://arbiscan.io/address/0x11cDb42B0EB46D95f990BeDD4695A6e3fA034978
  address internal constant CRV = 0x11cDb42B0EB46D95f990BeDD4695A6e3fA034978;

  // https://arbiscan.io/address/0x498Bf2B1e120FeD3ad3D42EA2165E9b73f99C1e5
  address internal constant CRVUSD = 0x498Bf2B1e120FeD3ad3D42EA2165E9b73f99C1e5;
}
