// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

library AssetsArbitrum {
  // https://arbiscan.io/address/0x82aF49447D8a07e3bd95BD0d56f35241523fBab1
  address internal constant WETH = 0x82aF49447D8a07e3bd95BD0d56f35241523fBab1;

  // https://arbiscan.io/address/0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f
  address internal constant WBTC = 0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f;

  // https://arbiscan.io/address/0x8c6Bd546fB8B53fE371654a0E54D7a5bD484b319
  address internal constant GOA = 0x8c6Bd546fB8B53fE371654a0E54D7a5bD484b319;

  // https://arbiscan.io/address/0x912CE59144191C1204E64559FE8253a0e49E6548
  address internal constant ARB = 0x912CE59144191C1204E64559FE8253a0e49E6548;

  // https://arbiscan.io/address/0x11cDb42B0EB46D95f990BeDD4695A6e3fA034978
  address internal constant CRV = 0x11cDb42B0EB46D95f990BeDD4695A6e3fA034978;

  // https://arbiscan.io/address/0x498Bf2B1e120FeD3ad3D42EA2165E9b73f99C1e5
  address internal constant CRVUSD = 0x498Bf2B1e120FeD3ad3D42EA2165E9b73f99C1e5;

  // https://arbiscan.io/address/0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9
  address internal constant USDT = 0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9;

  // https://arbiscan.io/address/0xaf88d065e77c8cC2239327C5EDb3A432268e5831
  address internal constant USDC = 0xaf88d065e77c8cC2239327C5EDb3A432268e5831;

  // https://arbiscan.io/address/0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8
  address internal constant USDCe = 0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8;

  // https://arbiscan.io/address/0xFEa7a6a0B346362BF88A9e4A88416B77a57D6c2A
  address internal constant MIM = 0xFEa7a6a0B346362BF88A9e4A88416B77a57D6c2A;

  // https://arbiscan.io/address/0x0c880f6761F1af8d9Aa9C466984b80DAb9a8c9e8
  address internal constant PENDLE = 0x0c880f6761F1af8d9Aa9C466984b80DAb9a8c9e8;

  // https://arbiscan.io/address/0xBfbCFe8873fE28Dfa25f1099282b088D52bbAD9C
  address internal constant EQB = 0xBfbCFe8873fE28Dfa25f1099282b088D52bbAD9C;
}
