// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

library ProtocolArbitrum {
  // https://arbiscan.io/address/0x5BE13f90cD86a8bb0f0573B550f04b95927F5dc5
  address internal constant TREASURY = 0x5BE13f90cD86a8bb0f0573B550f04b95927F5dc5;

  // https://arbiscan.io/address/0x2C568371E48744E65d5301Bba014c64Ca75d044E
  address internal constant TIMELOCK = 0x2C568371E48744E65d5301Bba014c64Ca75d044E;

  // https://arbiscan.io/address/0x03dc58ebe79E05F6524126821A6E9906F5704e58
  address internal constant FEE_CONFIG = 0x03dc58ebe79E05F6524126821A6E9906F5704e58;

  // https://arbiscan.io/address/0x108e823a26C5FB096D1f7c493809ccE9015507a6
  address internal constant MULTICALL = 0x108e823a26C5FB096D1f7c493809ccE9015507a6;

  // https://arbiscan.io/address/0xE06f5E3039901C1C16C7044fd3238987db8e688a
  address internal constant GOAT_APP_MULTICALL = 0xE06f5E3039901C1C16C7044fd3238987db8e688a;

  // https://arbiscan.io/address/0x98B332784678a919489FC05B81Ef5B20BbDdD5BA
  address internal constant GOAT_VAULT_FACTORY = 0x98B332784678a919489FC05B81Ef5B20BbDdD5BA;

  // https://arbiscan.io/address/0x667Fe8DD40969A5fB92b53e9C8503b454E569BDB
  address internal constant LAYERZERO_BRIDGE_ADAPTER = 0x667Fe8DD40969A5fB92b53e9C8503b454E569BDB;

  // https://arbiscan.io/address/0xeb8d830bd399cbDD55eEcc011E02a027DDD0d25b
  address internal constant GOAT_FEE_BATCH = 0xeb8d830bd399cbDD55eEcc011E02a027DDD0d25b;

  // https://arbiscan.io/address/0xA0eFC7056986411e02bC3fCdD82CCdfd9D3AB3A2
  address internal constant GOAT_REWARD_POOL = 0xA0eFC7056986411e02bC3fCdD82CCdfd9D3AB3A2;
}
