name: Harvest

on:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: default

jobs:
  check:
    strategy:
      fail-fast: true
  
    env:
        HARVESTER_PK: ${{ secrets.HARVESTER_PK }}
        MAINNET_RPC_URL: ${{secrets.MAINNET_RPC_URL}}
        ARBITRUM_RPC_URL: ${{ secrets.ARBITRUM_RPC_URL }}
  
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
  
      - uses: PaulRBerg/foundry-multibuild@v1
        with:
          min: "0.8.20"
          max: "0.8.20"
          skip-test: "false"
  
      - name: "Run Harvester"
        timeout-minutes: 10
        run: 'forge script GoatHarvester --rpc-url ${{env.ARBITRUM_RPC_URL}} --broadcast --skip-simulation --slow'