name: Harvester V2

on:
  schedule:
      - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  check:
    strategy:
      fail-fast: true
  
    env:
        HARVESTER_PK: ${{ secrets.HARVESTER_PK }}
        ARBITRUM_RPC_WEBSOCKET: ${{ secrets.ARBITRUM_RPC_WEBSOCKET }}
        BASE_RPC_WEBSOCKET: ${{ secrets.BASE_RPC_WEBSOCKET}}
  
    name: Harvester
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
  
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - run: bun install
  
      - name: "Run Harvester"
        timeout-minutes: 5
        run: "bun run scripts/harvester/harvester.ts --broadcast"