name: Harvest

on:
    schedule:
        - cron: "0 */6 * * *"

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true
  
    env:
        HARVESTER_PK: ${{ secrets.HARVESTER_PK }}
        MAINNET_RPC_URL: ${{secrets.MAINNET_RPC_URL}}
        ARBITRUM_RPC_URL: ${{ secrets.ARBITRUM_RPC_URL }}
  
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
  
      - uses: PaulRBerg/foundry-multibuild@v1
        with:
          min: "0.8.20"
          max: "0.8.20"
          skip-test: "false"

      - name: "Get Gas Price"
        run: 'echo -n $(cast gas-price --rpc-url ${{env.MAINNET_RPC_URL}}) > gas-price'
  
      - name: "Run Harvester"
        run: 'forge script GoatHarvester --rpc-url ${{env.ARBITRUM_RPC_URL}} --with-gas-price 0.1gwei --broadcast'

      - name: "Cleanup"
        run: 'rm gas-price'